### ISSUE TITLE
Prepare CI/CD pipelines for GitHub enterprise

### ISSUE THREAD

**Issue by graduad** [DolbyIO/comms-sdk-flutter#211]
GitHub enterprise comes with a set of security features that will disable actions:
- not created by GitHub
- not created and hosted by us
- not verified by GItHub
- not whitelisted.

This could serve as an example: https://github.com/dolbyio-samples/dolbyio-spatial-audio-demo-web/blob/main/.github/workflows/deploy-to-gh-pages.yml

**Comment by kbetl-dlb** [comment]
Use flutter-action and setup-dart as a local action: https://github.com/DolbyIO/comms-sdk-flutter/pull/251
