### ISSUE TITLE
[Android] Screenshare is crashing a test app of other android users

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#224]
Environment:
SDK Version: 3.6.1 - https://github.com/DolbyIO/comms-sdk-flutter/releases/tag/3.6.1:
Client Platform: Flutter test app. 

Description/Steps-to-reproduce:
-Install the QA test app
-Connect to the conference 1st Android device
-Connect to the conference 2nd Android device (you can connect as many devices as you want)
-Start screenshare as 1st Android device 

Expected result:
Screenshare is working properly.

Actual result:
Screenshare IS NOT working (bug: https://jira.dolby.net/jira/browse/CCS-4029) but that is not the case here. After clicking "Start screenshare" every participant which is on android system is kicked out from the conference and test app crashes from it's side. This is reproducing when user is trying to reconnect to the conference. iOS users test app is working fine and they are not kicked from the conference. 

Devices:
DV-WRO-SAM96 Samsung Galaxy TAB S8 + Android 12
DV-WRO-SAM98 Samsung Galaxy Tab S8 Ultra + Android 12
DV-WRO-SAM90 Samsung S22 Plus + Android 12
Private Phone Poco X3 NFC + Android 12

**Comment by kszku-dolby** [comment]
Fixed by @azduda

**Comment by kszku-dolby** [comment]
Reproduced on 3.7.0 beta.1 - https://github.com/DolbyIO/comms-sdk-flutter/releases/tag/3.7.0-beta.1

This time iOS device also can screenshare and then random Android device is disconnected. Reconnecting to the conference by crashed user is not possible until the screenshare is stopped.

**Comment by kszku-dolby** [comment]
Reproduced on develop branch https://github.com/DolbyIO/comms-sdk-flutter/pull/253 using(these devices crashed):
DV-WRO-SAM90 - samsung s22 Plus + Android 12
DV-WRO-SAM96 - Samsung Tab S8 + Android 12

**Comment by graduad** [comment]
This will be fixed by a new version of the Android native SDK.
