### ISSUE TITLE
[Android] Application crashes when trying to log in to a new session after leaving a conference with close session option

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#227]
Environment
Flutter version: 3.6.1 https://github.com/DolbyIO/comms-sdk-flutter/tree/release/3.6.1
Client Platform: Flutter test app. 

Description/Steps-to-reproduce:
-Install the QA test app on Android device
-Connect to the conference
-Leave the conference with close session option
-Login in to a new session

Expected result:
Logged in successfully

Actual result:
The application crashes when you click 'Login'
The bug does not always reproduce
You need at least 4 users in the conference (in our case it was 2 Androids and 2 iOS devices)

Devices:
any Android device

**Comment by codlab** [comment]
Related to #226, the fix will prevent this situation to happen

**Comment by codlab** [comment]
The Android SDK 3.7.3 should be fixing the issues regarding leave and join calls made in parallel by having the internal state managed transparently for developers, the flutter SDK will need to update the version used to ship this fix

**Comment by graduad** [comment]
No longer an issue in 3.7.0
