### ISSUE TITLE
iOS test app crashes when trying to screenshare during Android user screenshare

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#229]
Environment
SDK 3.6.1 https://github.com/DolbyIO/comms-sdk-flutter/releases/tag/3.6.1
Client Platform: Flutter test app. 

Description/Steps-to-reproduce:
-Install the QA test app
-Connect to the conference
-Start screenshare on Android (screen share at this moment is not working, but that is not the case)
-Try to start the screenshare on iOS, while Android did not stopped the screenshare, get an error
-Stop screenshare on Android

Expected result:
Android stops screenshare and nothing happens

Actual result:
iOS test app crashes

Devices:
DV-WRO-iOS66 iPhone XS Max + iOS16
Poco X3 NFC + Android 12
DV-WRO-IOS108 iPhone 13 Pro Max + iOS 15
DV-WRO-SAM91 Samsung S22 Snapdragon + Android 12

**Comment by kbetl-dlb** [comment]
Screen is not supported at the same time for two devices. QA app does not longer allow this
