### ISSUE TITLE
[Android] [iOS] Change speaker does not work when headphones are used

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#231]
Environment: 
SDK Version: 3.6.1 
Client Platform: Flutter test app. Samsung S22 + Android 12

Description/Steps-to-reproduce:
-Install the QA test app
-Connect to the conference (There is no difference if you use Bluetooth or USB-C headphones or lightning headphones)
-Use "Change speaker" option

Expected result:
"Change speaker" option works, audio is audible on speakerphone.

Actual result:
"Change speaker" option does not work, audio is audible only on headphones.

Devices:
Any Android and iOS device

**Comment by kbetl-dlb** [comment]
This standard behavior for the ioS native sdk, and this behavior was copied to Android. Since we cannot change native SDK behavior in Flutter, we are closing this issue.
