### ISSUE TITLE
[iOS] Video starts from front camera instead of back

### ISSUE THREAD

**Issue by bciac** [DolbyIO/comms-sdk-flutter#246]
Environment:
SDK Version: 3.7.0-beta.1
Client Platform: Flutter test app. 

Description/Steps-to-reproduce:

    Join a conference
    Start video
    Change front camera to back
    Stop video and start video

Expected result:

    Video should start from back camera

Actual result:

    Video starts from front camera instead of back

Devices:

    Any iOS device

The problem is related to the iOS SDK
https://jira.dolby.net/jira/projects/CCS/issues/CCS-4191

**Comment by graduad** [comment]
Rase this with @srynk

**Comment by graduad** [comment]
Deemed to be standard behaviour for the moment.
