### ISSUE TITLE
[Android] Bluetooth and usb-c headphones are switching each other

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#273]
Environment

SDK Version: 3.7.0 - https://github.com/DolbyIO/comms-sdk-flutter/tree/release/3.7.0
Client Platform: Flutter test app.

Description/Steps-to-reproduce:
-Install the QA test app
-Connect usb-c headphones to device
-Connect to the conference
-Connect bluetooth headphones to device
-Unplug usb-c headphones
-Plug usb-c headphones

Expected result:
Nothing happens/devices are working properly

Actual result:
Device management gets in some kind of loop - usb-c and bluetooth headphones are switching each other every second (sometimes it takes break for 20 seconds, then starts again) 

Devices:
Poco X3 + Android 12
Huawei USB-C Headphones 
Samsung Galaxy Buds Pro

TICKET COPIED FROM ANDROID SDK BUG (which was fixed one month ago), PROBABLY SAME ISSUE: https://jira.dolby.net/jira/browse/CCS-4099

**Comment by codlab** [comment]
https://github.com/DolbyIO/comms-sdk-flutter/blob/release/3.7.0/android/build.gradle#L6

Yup, the SDK version set is 3.7.0, fixed in 3.7.2 (3.7.3 is the newest one tho)

**Comment by kszku-dolby** [comment]
Fixed on 3.7.3
