### ISSUE TITLE
[Android] Unknown iOS user status from the conference 

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#276]
Environment

SDK Version: 3.7.0 - https://github.com/DolbyIO/comms-sdk-flutter/tree/release/3.7.0
Client Platform: Flutter test app.

Description/Steps-to-reproduce:
-Install the QA test app
- The other user from 1st iOS device creates the conference
- Connect to this conference from 1st Android device
- Connect to this conference from 2nd Android device
- Connect to this conference from 2nd iOS device

Expected result:
All users are connected and their status is visible (connected/on_air)
Actual result:
On Android devices status of the ios users is not visible - UNKNOWN
![smoke2](https://user-images.githubusercontent.com/109804819/208412595-9b04465f-c53a-4e61-8672-e199c4e8e7c9.jpeg)

**Comment by RafidKhan** [comment]
Facing the same issue. 
await dolbyioCommsSdk.conference.join(conference!, joinOptions);
this is where I am getting error. any update about the issue?
