### ISSUE TITLE
Ios android cross platform user not getting detected

### ISSUE THREAD

**Issue by RafidKhan** [DolbyIO/comms-sdk-flutter#289]
A am developing an app that uses this sdk for voice conference. The app I am developing is for android. On the other hand, there is already another ios version of the app that is being developed by someone else. I was provided consumerkey and consumer secret. When I start a voice chat from android, as an admin, every users can mute/unmute themselves. This is expected behaviour. But when conference is started from ios device as admin, android users are b y default unmuted and can't mute/unmute themselves. They are unmuted always. I have figured out on flutter code, dolbyioCommsSdk.conference.join(conference, joinOptions) is not getting triggered. Any idea how can I get the issue fixed?Ios code is written in Swift

**Comment by RafidKhan** [comment]
ios code is written in Swift, letting you know

**Comment by RafidKhan** [comment]
A am developing an app that uses this sdk for voice conference. The app I am developing is for android. On the other hand, there is already another ios version of the app that is being developed by someone else. I was provided consumerkey and consumer secret. When I start a voice chat from android, as an admin, every users can mute/unmute themselves. This is expected behaviour. But when conference is started from ios device as admin, android users are b y default unmuted and can't mute/unmute themselves. They are unmuted always. I have figured out on flutter code, dolbyioCommsSdk.conference.join(conference, joinOptions) is not getting triggered. Any idea how can I get the issue fixed? Ios code is written in Swift

**Comment by graduad** [comment]
Perhaps defaults for iOS and Android are different. We need to check this.

**Comment by RafidKhan** [comment]
I have tested on Samsung m21, android version 12 ,sdk version 3.7.0. On ios I have tested on Iphone 7, ios version 15.7.1.Ios used voxeet sdk, which is equivalent to dolbyio_comms_sdk_flutter as per documentation

**Comment by mpozy** [comment]
Hi @RafidKhan, was it conference with dolbyVoice or not?

**Comment by RafidKhan** [comment]
no. it is false
```
var params = ConferenceCreateParameters();
params.dolbyVoice = false;
```

this is my code

**Comment by mpozy** [comment]
If conference is started from iOS, conference parameters are set by iOS. You need to check your conference create parameters for iOS app (dolby voice is set on true by default). In conferences with dolby voice you should use AudioService methods instead of mute method. Mute method is supported in non-dolby voice conferences. Please share your create and join options for both apps and error message.

**Comment by RafidKhan** [comment]
Android Code: 
`Future<void> joinConferenceSdk() async {
    try {
      var params = ConferenceCreateParameters();
      var createOptions = ConferenceCreateOption(
          widget.groupId, params, 0, SpatialAudioStyle.individual);
      var joinOptions = ConferenceJoinOptions();
      params.dolbyVoice = false;
      joinOptions.constraints = ConferenceConstraints(true, false);
      voiceChatController.conference = await voiceChatController
          .dolbyioCommsSdk.conference
          .create(createOptions);
      if (voiceChatController.conference != null) {
        var status = voiceChatController.conference!.status;
        if (status.name.trim() == 'created') {
          voiceChatController.conference?.alias = widget.groupId;
          await voiceChatController.dolbyioCommsSdk.conference
              .join(voiceChatController.conference!, joinOptions);
          voiceChatController.muteSpecificUser(
              userId: userController.userId.value);
          voiceChatController.onParticipantsChangeSubscription =
              voiceChatController.dolbyioCommsSdk.conference
                  .onParticipantsChange()
                  .listen((params) {
            updateParticipantsList();
          });
          voiceChatController.onStreamsChangeSubscription = voiceChatController
              .dolbyioCommsSdk.conference
              .onStreamsChange()
              .listen((params) {
            updateParticipantsList();
          });

          EasyLoading.dismiss();
          setState(() {});
        }
      } else {
        EasyLoading.dismiss();

        setState(() {});
      }
    } catch (e) {
      EasyLoading.dismiss();
      setState(() {});
    }
  }`


IOS Code:
`func joinConference(groupId: String, completion: @escaping (_ success: Bool, _ exitFlow: Bool) -> Void) {
        /// Check for existing live conferences. If matches current group id, skip the creation/joining of a new conference
        if let currentConference = VoxeetSDK.shared.conference.current, currentConference.alias == groupId {
            completion(false, false)
            return
        }
        
        /// Leave any current conference, create a new one and join it
        startConference(groupId: groupId) { conference in
            if let conference = conference {
                VoxeetSDK.shared.conference.join(conference: conference, options: nil) { _ in
                    VoxeetSDK.shared.conference.mute(true)
                    self.activeVoiceChatGroupId = groupId
                    self.didJoinVoiceChat = true
                    self.isMicrophoneOn = false
                    completion(true, false)
                } fail: { error in
                    /// Failed to join the conference
                    presentAlert(title: "Join Chat", message: error.localizedDescription, primaryAction: UIAlertAction(title: "OK", style: .default, handler: { _ in
                        completion(false, false)
                    }))
                }
            } else { completion(false, true) }
        }
    }`

**Comment by RafidKhan** [comment]
Android Code:

```
Future<void> joinConferenceSdk() async {
    try {
      var params = ConferenceCreateParameters();
      var createOptions = ConferenceCreateOption(
          widget.groupId, params, 0, SpatialAudioStyle.individual);
      var joinOptions = ConferenceJoinOptions();
      params.dolbyVoice = false;
      joinOptions.constraints = ConferenceConstraints(true, false);
      voiceChatController.conference = await voiceChatController
          .dolbyioCommsSdk.conference
          .create(createOptions);
      if (voiceChatController.conference != null) {
        var status = voiceChatController.conference!.status;
        if (status.name.trim() == 'created') {
          voiceChatController.conference?.alias = widget.groupId;
          await voiceChatController.dolbyioCommsSdk.conference
              .join(voiceChatController.conference!, joinOptions);
          voiceChatController.muteSpecificUser(
              userId: userController.userId.value);
          voiceChatController.onParticipantsChangeSubscription =
              voiceChatController.dolbyioCommsSdk.conference
                  .onParticipantsChange()
                  .listen((params) {
            updateParticipantsList();
          });
          voiceChatController.onStreamsChangeSubscription = voiceChatController
              .dolbyioCommsSdk.conference
              .onStreamsChange()
              .listen((params) {
            updateParticipantsList();
          });

          EasyLoading.dismiss();
          setState(() {});
        }
      } else {
        EasyLoading.dismiss();

        setState(() {});
      }
    } catch (e) {
      EasyLoading.dismiss();
      setState(() {});
    }
  }
```


IOS Code:

 ```
func joinConference(groupId: String, completion: @escaping (_ success: Bool, _ exitFlow: Bool) -> Void) {
        /// Check for existing live conferences. If matches current group id, skip the creation/joining of a new conference
        if let currentConference = VoxeetSDK.shared.conference.current, currentConference.alias == groupId {
            completion(false, false)
            return
        }
        
        /// Leave any current conference, create a new one and join it
        startConference(groupId: groupId) { conference in
            if let conference = conference {
                VoxeetSDK.shared.conference.join(conference: conference, options: nil) { _ in
                    VoxeetSDK.shared.conference.mute(true)
                    self.activeVoiceChatGroupId = groupId
                    self.didJoinVoiceChat = true
                    self.isMicrophoneOn = false
                    completion(true, false)
                } fail: { error in
                    /// Failed to join the conference
                    presentAlert(title: "Join Chat", message: error.localizedDescription, primaryAction: UIAlertAction(title: "OK", style: .default, handler: { _ in
                        completion(false, false)
                    }))
                }
            } else { completion(false, true) }
        }
    }
```

**Comment by mpozy** [comment]
There are no create parameters for Swift code. Please share this.

**Comment by RafidKhan** [comment]
swift code for create:

```
private func openConferenceSession(groupId: String, completion: @escaping (_ conference: VTConference?) -> Void) {
        let options = VTConferenceOptions()
        options.params.dolbyVoice = false
        options.alias = groupId
        
        let info = VTParticipantInfo(externalID: self.currentUser?.userId, name: nil, avatarURL: nil)
        VoxeetSDK.shared.session.open(info: info) { error in
            if let errorMessage = error?.localizedDescription {
                /// Failed to create to open a session
                presentAlert(title: "Open Session", message: errorMessage, primaryAction: UIAlertAction(title: "OK", style: .default, handler: { _ in
                    completion(nil)
                }))
            } else {
                VoxeetSDK.shared.conference.create(options: options) { conference in
                    completion(conference)
                } fail: { error in
                    /// Failed to create the conference
                    presentAlert(title: "Create Chat", message: error.localizedDescription, primaryAction: UIAlertAction(title: "OK", style: .default, handler: { _ in
                        completion(nil)
                    }))
                }
            }
        }
    }
```

**Comment by RafidKhan** [comment]
I am not getting any error message or exception on flutter. It  just stucks at dolbyioCommsSdk.conference.join(conference, joinOptions)

**Comment by ayon115** [comment]
@mpozy any update on this issue?

**Comment by graduad** [comment]
Unfortunately so far we were not able to reproduce the issue. 

Also what do you mean by `It just stucks at dolbyioCommsSdk.conference.join(...)`. Are the statements after this not executed at all? Or is it something else?

**Comment by rafidgithub** [comment]
the code after dolbyioCommsSdk.conference.join(...) is not being executed

**Comment by graduad** [comment]
@RafidKhan, Is this still an issue? If so please let us know. And please make sure to upgrade to the latest SDK version.

**Comment by graduad** [comment]
Closing the issue as we cannot reproduce, and no recent feedback from customer is available.
