### ISSUE TITLE
Incorrect dolbyVoice default value in ConferenceCreateParameters.

### ISSUE THREAD

**Issue by mpozy** [DolbyIO/comms-sdk-flutter#385]
Documentation says that dolbyVoice by default is set to true, but in FlutterSDK it's false.

**Comment by graduad** [comment]
In the code we have to follow the documentation. Ie. the default should be true.

**Comment by mpozy** [comment]
Documentation: https://api-references.dolby.io/comms-sdk-flutter/dolbyio_comms_sdk_flutter/ConferenceCreateParameters-class.html
